/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'ashish' at '6/7/16 2:54 PM' with Gradle 2.7
 *
 * @author ashish, @date 6/7/16 2:54 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
