/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'ashish' at '6/7/16 2:54 PM' with Gradle 2.7
 *
 * @author ashish, @date 6/7/16 2:54 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
